// import Head from "next/head"
// import Image from "next/image"
// import axios from 'axios'
// import {useState} from 'react'
// import {BsSearch} from 'react-icons/bs'

// export default function Home() {
//     const [city, setCity ] = useState('');
//     const [weather, setWeather] = useState({});
//     const [loading, setLoading] = useState(false);

//     const fetchWeather = (e) => {
//         e.preventDefault();
//         setLoading(true);
//         const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=imperial&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`;
//         axios.get(url).then((response) => {
//             setWeather(response.data);
//             console.log(response.data);
//             setCity('');
//             setLoading(false);
//         }).catch((error) => {
//             console.error('Error fetching weather:', error);
//             setLoading(false);
//         });
//     };

//     return (
//         <div>
//             <Head>
//                 <title>Weather - Next App</title>
//                 <meta name="description" content="Generated by create next app" />
//                 <link rel="icon" href="/favicon.ico" />
//             </Head>
//             <Image
//             src='https://images.unsplash.com/photo-1563974318767-a4de855d7b43?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTIyfHx3ZWF0aGVyfGVufDB8fDB8fHww'
//              layout='fill'
//                 />
        
//                 <div>
//                     {weather.main && (
//                         <div>
//                             <h2>{weather.name}</h2>
//                             <p>Temperature: {weather.main.temp}°F</p>
//                             <p>Humidity: {weather.main.humidity}%</p>
//                             <p>Weather: {weather.weather[0].description}</p>
//                         </div>
//                     )}
//                 </div>
        
//         </div>
//     );
// }
import Head from "next/head"
import Image from "next/image"

export default function Home() {
return (
    <div>
        <Head>
         <title>Weather - Next App</title>
               <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />          
       </Head>
       <h1>Hello</h1>

    </div>
)
}